export const CHANGE_LOGIN_ID = 'LOGIN_ACTION_CHANGE_LOGIN_ID';
export const CHANGE_PASSWORD = 'LOGIN_ACTION_CHANGE_PASSWORD';
export const SAVE_AUTHORIZATION = 'LOGIN_ACTION_SAVE_AUTHORIZATION';
export const CLEAR_AUTHORIZATION = 'LOGIN_ACTION_CLEAR_AUTHORIZATION';
export const CLEAR_LOGIN_ID_AND_PASSWORD = 'LOGIN_ACTION_CLEAR_LOGIN_ID_AND_PASSWORD';
export const SAVE_PASSENGER = 'LOGIN_ACTION_SAVE_PASSENGER';